name: authenticate
description: Authentication logic package
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
